version: "3.7"

services: 
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - ${MYSQL_PORT}:${MYSQL_PORT_EXPOSE_CONTAINER}
    expose:
      # Opens port 3306 on the container
      - ${MYSQL_PORT_EXPOSE_CONTAINER}
       
  phpmyadmin:
    image: 'phpmyadmin:latest'  
    ports:
      - 8088:80
    environment:      
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
networks:
  proxy:
    external: true