version: "3.7"

services: 
  db:
    image: mysql:5.7
    restart: always
    environment:     
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   
  phpmyadmin:
    image: 'phpmyadmin:latest'  
    ports:
      - 8088:80
    environment:      
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
networks:
  proxy:
    external: true